# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-19 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.TextField(verbose_name='\u6210\u679c\u6587\u4ef6\u8def\u5f84')),
                ('serverIP', models.CharField(max_length=500, null=True, verbose_name='\u6240\u5c5e\u670d\u52a1\u5668')),
            ],
            options={
                'verbose_name': '\u6210\u679c\u6587\u4ef6',
                'verbose_name_plural': '\u6210\u679c\u6587\u4ef6',
            },
        ),
    ]
