# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-18 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultfile',
            name='file_path',
            field=models.CharField(max_length=12800, verbose_name='\u6210\u679c\u6587\u4ef6\u8def\u5f84'),
        ),
    ]
