# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-21 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultfile',
            name='dirdepth',
            field=models.IntegerField(null=True, verbose_name='\u76ee\u5f55\u6df1\u5ea6'),
        ),
        migrations.AddField(
            model_name='resultfile',
            name='dirlength',
            field=models.IntegerField(null=True, verbose_name='\u76ee\u5f55\u6df1\u5ea6'),
        ),
    ]
