# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-18 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20190318_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultfile',
            name='file_path',
            field=models.TextField(verbose_name='\u6210\u679c\u6587\u4ef6\u8def\u5f84'),
        ),
    ]
