# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20190323_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileinfo',
            old_name='type',
            new_name='resulttype',
        ),
        migrations.RenameField(
            model_name='fileinfo',
            old_name='year',
            new_name='resultyear',
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='handoutlist_name',
            field=models.CharField(max_length=5000, verbose_name='\u8be5\u6210\u679c\u6240\u5c5e\u6e05\u5355'),
        ),
        migrations.AlterField(
            model_name='filepath',
            name='handoutlist_name',
            field=models.CharField(max_length=5000, null=True, verbose_name='\u8be5\u6210\u679c\u6240\u5c5e\u6e05\u5355'),
        ),
    ]
