# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-19 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20190318_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultfile',
            old_name='file_path',
            new_name='filepath',
        ),
        migrations.RenameField(
            model_name='resultfile',
            old_name='server_allow',
            new_name='serverIP',
        ),
    ]
