# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20190325_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='mediumtype',
        ),
        migrations.RemoveField(
            model_name='handoutlist',
            name='deliveryway',
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='cdmedia',
            field=models.BooleanField(default=False, verbose_name='\u5149\u76d8\u4ecb\u8d28'),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='cdmedianum',
            field=models.CharField(max_length=2000, null=True, verbose_name='\u5149\u76d8\u4ecb\u8d28\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='diskmedia',
            field=models.BooleanField(default=False, verbose_name='\u786c\u76d8\u4ecb\u8d28'),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='diskmedianum',
            field=models.CharField(max_length=2000, null=True, verbose_name='\u786c\u76d8\u4ecb\u8d28\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='networkmedia',
            field=models.BooleanField(default=False, verbose_name='\u7f51\u7edc\u4ecb\u8d28'),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='othermedia',
            field=models.BooleanField(default=False, verbose_name='\u5176\u4ed6\u4ecb\u8d28'),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='othermedianum',
            field=models.CharField(max_length=5000, null=True, verbose_name='\u5176\u4ed6\u4ecb\u8d28\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='papermedia',
            field=models.BooleanField(default=False, verbose_name='\u7eb8\u8d28\u4ecb\u8d28'),
        ),
        migrations.AddField(
            model_name='handoutlist',
            name='deliverway',
            field=models.BooleanField(default=False, verbose_name='\u9012\u9001\u65b9\u5f0f\u4e3a\u9001\u5f80'),
        ),
        migrations.AddField(
            model_name='handoutlist',
            name='networkway',
            field=models.BooleanField(default=False, verbose_name='\u9012\u9001\u65b9\u5f0f\u4e3a\u7f51\u7edc'),
        ),
        migrations.AddField(
            model_name='handoutlist',
            name='otherway',
            field=models.BooleanField(default=False, verbose_name='\u9012\u9001\u65b9\u5f0f\u4e3a\u5176\u4ed6'),
        ),
        migrations.AddField(
            model_name='handoutlist',
            name='otherwaydetail',
            field=models.CharField(max_length=1000, null=True, verbose_name='\u5176\u4ed6\u9012\u9001\u65b9\u5f0f\u8be6\u7ec6\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='handoutlist',
            name='postway',
            field=models.BooleanField(default=False, verbose_name='\u9012\u9001\u65b9\u5f0f\u4e3a\u90ae\u5bc4'),
        ),
        migrations.AddField(
            model_name='handoutlist',
            name='selfgetway',
            field=models.BooleanField(default=False, verbose_name='\u9012\u9001\u65b9\u5f0f\u4e3a\u81ea\u53d6'),
        ),
    ]
