# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20190325_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='name',
            field=models.CharField(max_length=5000, verbose_name='\u6210\u679c\u8d44\u6599\u540d\u79f0'),
        ),
    ]
