# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-28 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_remove_fileinfo_mediumnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultfile',
            name='filecreatetime',
            field=models.DateTimeField(null=True, verbose_name='\u6587\u4ef6\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='resultfile',
            name='filesize',
            field=models.FloatField(null=True, verbose_name='\u6587\u4ef6\u5927\u5c0f,\u5355\u4f4d: MB'),
        ),
        migrations.AddField(
            model_name='resultfile',
            name='fileupdatetime',
            field=models.DateTimeField(null=True, verbose_name='\u6587\u4ef6\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
