# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-28 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_auto_20190328_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoutlist',
            name='name',
            field=models.CharField(max_length=5000, unique=True, verbose_name='\u6210\u679c\u4ea4\u4ed8\u6e05\u5355\u540d\u79f0'),
        ),
    ]
