# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-04 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_auto_20190328_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoutlist',
            name='name',
            field=models.CharField(error_messages={'unique': '名称已存在'}, max_length=5000, unique=True, verbose_name='成果交付清单名称'),
        ),
    ]
