# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-12 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_auto_20190404_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='cdmedianum',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='光盘介质编号'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='datasize',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='成果数据量GB'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='diskmedianum',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='硬盘介质编号'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='num',
            field=models.IntegerField(blank=True, null=True, verbose_name='成果数量'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='othermedianum',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='其他介质编号'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='resulttype',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='成果类型'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='resultyear',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='成果年代'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='secretlevel',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='成果秘密级别'),
        ),
        migrations.AlterField(
            model_name='filepath',
            name='fileinfo_name',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='成果资料名称'),
        ),
        migrations.AlterField(
            model_name='filepath',
            name='filepath',
            field=models.TextField(blank=True, null=True, verbose_name='成果文件路径'),
        ),
        migrations.AlterField(
            model_name='filepath',
            name='handoutlist_name',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='该成果所属清单'),
        ),
        migrations.AlterField(
            model_name='handoutlist',
            name='auditnum',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='审核编号'),
        ),
        migrations.AlterField(
            model_name='handoutlist',
            name='handler',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='清单经办人'),
        ),
        migrations.AlterField(
            model_name='handoutlist',
            name='handovertime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='交接日期'),
        ),
        migrations.AlterField(
            model_name='handoutlist',
            name='listnum',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='清单受理编号'),
        ),
        migrations.AlterField(
            model_name='handoutlist',
            name='otherwaydetail',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='其他递送方式详细信息'),
        ),
        migrations.AlterField(
            model_name='handoutlist',
            name='purpose',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='用途'),
        ),
        migrations.AlterField(
            model_name='handoutlist',
            name='receiver',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='接收人'),
        ),
        migrations.AlterField(
            model_name='handoutlist',
            name='receiverinfo',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='接收人联系方式'),
        ),
        migrations.AlterField(
            model_name='handoutlist',
            name='receiveunit',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='接收单位'),
        ),
        migrations.AlterField(
            model_name='handoutlist',
            name='recievetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='接收日期'),
        ),
        migrations.AlterField(
            model_name='handoutlist',
            name='secretlevel',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='清单秘密级别'),
        ),
        migrations.AlterField(
            model_name='handoutlist',
            name='undertaker',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='承办参谋'),
        ),
    ]
