# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-17 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0011_auto_20190412_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultFile',
        ),
    ]
