# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-18 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0012_delete_resultfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='num',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='成果数量'),
        ),
    ]
