# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-22 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reallyname',
            field=models.CharField(max_length=1000, null=True, verbose_name='\u771f\u5b9e\u59d3\u540d'),
        ),
    ]
