# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-17 11:35
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190404_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isadmin',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u7ba1\u7406\u5458'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
    ]
